name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install node_modules
        run: pnpm install --no-frozen-lockfile
        working-directory: .

      - name: Build site
        run: pnpm build
        working-directory: .
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'pdf-to-images'
          entrypoint: https://deno.land/std/http/file_server.ts
          root: dist
